apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: nexus-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
      - name: server
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nexus-lms-server:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/v1/courses # Or any public endpoint
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/courses
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        envFrom:
        - secretRef:
            name: nexus-secrets
        - configMapRef:
            name: nexus-config
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: nexus-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
