apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: nexus-lms.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nexus-server
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-client
            port:
              number: 80
  tls:
  - hosts:
    - nexus-lms.com
    secretName: nexus-tls
