apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server-deployment.yaml
  - client-deployment.yaml
  - ingress.yaml
  # - secrets.yaml # Secrets usually managed externally or via sealed-secrets
  # - configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: nexus-lms
