apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
      - name: nexus-server
        image: nexus-server
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: nexus-secrets
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-server
spec:
  selector:
    app: nexus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
